// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import VYouCore

/**
 * selector: ClassContext/com.vyou:vyou-kmm-client/com/vyou/kmm/client/VYouField */
public enum VYouFieldKs {

  case date(VYouFieldDate)
  case email(VYouFieldEmail)
  case number(VYouFieldNumber)
  case text(VYouFieldText)

  public var sealed: VYouField {
    switch self {
    case .date(let obj):
      return obj as! VYouCore.VYouField
    case .email(let obj):
      return obj as! VYouCore.VYouField
    case .number(let obj):
      return obj as! VYouCore.VYouField
    case .text(let obj):
      return obj as! VYouCore.VYouField
    }
  }

  public init(_ obj: VYouField) {
    if let obj = obj as? VYouCore.VYouFieldDate {
      self = .date(obj)
    } else if let obj = obj as? VYouCore.VYouFieldEmail {
      self = .email(obj)
    } else if let obj = obj as? VYouCore.VYouFieldNumber {
      self = .number(obj)
    } else if let obj = obj as? VYouCore.VYouFieldText {
      self = .text(obj)
    } else {
      fatalError("VYouFieldKs not synchronized with VYouField class")
    }
  }

}

/**
 * selector: ClassContext/com.vyou:vyou-kmm-client/com/vyou/kmm/client/VYouSignInProvider */
public enum VYouSignInProviderKs {

  case apple(VYouSignInProvider.Apple)
  case facebook(VYouSignInProvider.Facebook)
  case google(VYouSignInProvider.Google)
  case userPassword(VYouSignInProvider.UserPassword)

  public init(_ obj: VYouSignInProvider) {
    if let obj = obj as? VYouCore.VYouSignInProvider.Apple {
      self = .apple(obj)
    } else if let obj = obj as? VYouCore.VYouSignInProvider.Facebook {
      self = .facebook(obj)
    } else if let obj = obj as? VYouCore.VYouSignInProvider.Google {
      self = .google(obj)
    } else if let obj = obj as? VYouCore.VYouSignInProvider.UserPassword {
      self = .userPassword(obj)
    } else {
      fatalError("VYouSignInProviderKs not synchronized with VYouSignInProvider class")
    }
  }

}
